### ISSUE TITLE
Failing to register the BouncyCastle

### ISSUE THREAD

**Issue by MathildeLemee** [crashub/spring-ehcache-demo#1]
When launching the webapp 

09:11:05,156 INFO  [org.apache.sshd.common.util.SecurityUtils](MSC service thread 1-3) Trying to register BouncyCastle as a JCE provider
09:11:05,199 ERROR [org.apache.sshd.common.util.SecurityUtils](MSC service thread 1-3) Failed to register BouncyCastle as the defaut JCE provider
09:11:05,199 ERROR [org.crsh.ssh.term.SSHLifeCycle](MSC service thread 1-3) Could not start CRaSSHD: java.lang.RuntimeException: Failed to register BouncyCastle as the defaut JCE provider
    at org.apache.sshd.common.util.SecurityUtils.register(SecurityUtils.java:83) [crsh.shell.ssh-1.1.0-standalone.jar:]
    at org.apache.sshd.common.util.SecurityUtils.isBouncyCastleRegistered(SecurityUtils.java:68) [crsh.shell.ssh-1.1.0-standalone.jar:]
    at org.apache.sshd.SshServer.setUpDefaultServer(SshServer.java:430) [crsh.shell.ssh-1.1.0-standalone.jar:]
    at org.crsh.ssh.term.SSHLifeCycle.doInit(SSHLifeCycle.java:97) [crsh.shell.ssh-1.1.0-standalone.jar:]
    at org.crsh.term.TermLifeCycle.init(TermLifeCycle.java:46) [crsh.shell.core-1.1.0-standalone.jar:]

JBoss AS 7.1.1 + mac osx

:)

**Comment by drieu** [comment]
Hi,

It's a common error.We will probably put in a FAQ.
See
http://totalprogus.blogspot.fr/2012/09/crash-could-not-start-crasshd-failed-to.html
.

kind regards,

2012/11/13 MathildeLemee notifications@github.com

> When launching the webapp
> 
> 09:11:05,156 INFO org.apache.sshd.common.util.SecurityUtilshttp://MSC%20service%20thread%201-3Trying to register BouncyCastle as a JCE provider
> 09:11:05,199 ERROR org.apache.sshd.common.util.SecurityUtilshttp://MSC%20service%20thread%201-3Failed to register BouncyCastle as the defaut JCE provider
> 09:11:05,199 ERROR org.crsh.ssh.term.SSHLifeCyclehttp://MSC%20service%20thread%201-3Could not start CRaSSHD: java.lang.RuntimeException: Failed to register
> BouncyCastle as the defaut JCE provider
> at
> org.apache.sshd.common.util.SecurityUtils.register(SecurityUtils.java:83)
> [crsh.shell.ssh-1.1.0-standalone.jar:]
> at
> org.apache.sshd.common.util.SecurityUtils.isBouncyCastleRegistered(SecurityUtils.java:68)
> [crsh.shell.ssh-1.1.0-standalone.jar:]
> at org.apache.sshd.SshServer.setUpDefaultServer(SshServer.java:430)
> [crsh.shell.ssh-1.1.0-standalone.jar:]
> at org.crsh.ssh.term.SSHLifeCycle.doInit(SSHLifeCycle.java:97)
> [crsh.shell.ssh-1.1.0-standalone.jar:]
> at org.crsh.term.TermLifeCycle.init(TermLifeCycle.java:46)
> [crsh.shell.core-1.1.0-standalone.jar:]
> 
> JBoss AS 7.1.1 + mac osx
> 
> :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/crashub/spring-ehcache-demo/issues/1.

## 

Rieu Damien

Pôle d'intégration SIRHEN
Rectorat Aix-Marseille
Tél: 04.42.93.96.17
Fax: 04.42.93.96.00
